# Generated by Django 3.2 on 2021-06-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_calendar', '0003_scheduleevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
    ]
