# Generated by Django 3.2 on 2021-07-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop_calendar', '0005_admissionclass_classsanction_classscheduleevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classscheduleevent',
            unique_together={('schedule_class', 'class_sanction', 'name')},
        ),
    ]
