# Generated by Django 3.2 on 2021-07-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drop_calendar', '0008_alter_classscheduleevent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classscheduleevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='classscheduleevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
